#!/usr/bin/env bash
#
# ---------------------------------------------------------
# seqit | Lightweight tool for nucleotide sequence analysis 
# ---------------------------------------------------------
# Author:      Rish
# Date:        March 22, 2026
# License:     MIT
# ---------------------------------------------------------
#
#Color definitions
GREEN='\e[1;92m'
WHITE='\e[1;97m'
RESET='\e[0m'

usage() {
    echo "Usage: seqit <file.fasta>"
}

(($# == 0)) && { usage; exit 1; }

{ command -v bc && command -v tee; } >/dev/null || \
    { echo 'Missing dependencies: bc or tee'; exit 1; }

FILE="$1"

if [[ -f "$FILE" ]]; then
    RAW_INPUT=$(grep -v "^>" "$FILE" | tr -d '[:space:]')
    INPUT="${RAW_INPUT^^}"   # convert all chars. to uppercase
else
    echo "Error: File '$FILE' not found."
    usage; exit 1
fi

{
    echo "------ REPORT FOR: '$FILE' ------"
    echo; echo '>> Type: DNA'   # will include for RNA later
    COMP=$(tr 'ATGC' 'TACG' <<< "$INPUT" | fold -w 60)
    echo; echo -e ">> Complimentary"
    echo "$COMP"; echo
    R_COMP=$(tr -d '\n' <<< "$COMP" | rev | fold -w 60)
    echo -e ">> Reverse Complimentary" 
    echo "$R_COMP"; echo
} | tee -a ${FILE%.*}_seqit.fasta

count_char() {
    local base_str=$(tr -dc "$1" <<< "$INPUT")
    echo "${#base_str}"
}

ADEN=$(count_char "A") 
GUAN=$(count_char "G")
CYTO=$(count_char "C")
THYM=$(count_char "T")

{   echo "Adenine (A): $ADEN"
    echo "Guanine (G): $GUAN"
    echo "Cytosine(C): $CYTO"
    echo "Thymine (T): $THYM"
} | tee -a ${FILE%.*}_seqit.fasta

# calculation for GC and AT Content
TOTAL=${#INPUT}
if (( TOTAL > 0 )); then
    GC_COUNT=$(( GUAN + CYTO ))
    GC_PCT=$(bc -l <<< "scale=2; $GC_COUNT * 100 / $TOTAL" )
    {
        echo; echo -e "GC Content: $GC_PCT%"
    } | tee -a ${FILE%.*}_seqit.fasta

    AT_COUNT=$(( ADEN + THYM ))
    AT_PCT=$(bc -l <<< "scale=2; $AT_COUNT * 100 / $TOTAL")
    {
        echo -e "AT Content: $AT_PCT%"
    } | tee -a ${FILE%.*}_seqit.fasta
fi

echo -e "\n[ ${GREEN}DONE${RESET} ] Analysis saved to: ${WHITE}${1%.*}_seqit.fasta${RESET}"
