#!/usr/bin/env bash
#
# ---------------------------------------------------------
# Lightweight tool for nucleotide sequence analysis 
# ---------------------------------------------------------
# Author:      Rish
# Date:        March 21, 2026
# License:     MIT
# ---------------------------------------------------------
#
# Color definitions
WHITE='\e[1;37m'
NC='\e[0m'

usage() {
    echo "Usage: seqit [fasta file] or [sequence]"
    echo "Example: seqit myfile.fasta | myfile | myfile.txt"
    echo "Note: Its's highly recommended that you give sequence as file
      rather pasting the sequence directly cause it has to quoted"
}

(($# == 0)) && { usage; exit 1; }

if ! command -v bc >/dev/null 2>&1; then
    echo "Depends: 'bc' for floating-point calculation"
    echo "Run: pkg install bc"; exit 1
fi

if [[ -f "$1" ]]; then
    RAW_INPUT=$(grep -v "^>" "$1" | tr -d '[:space:]')
    INPUT="${RAW_INPUT^^}"      # convert all chars. to uppercase
else
    RAW_INPUT="${*// /}"        # quotes the args. as one string
    INPUT="${RAW_INPUT^^}"       
fi

COMP=$(tr 'ATGC' 'TACG' <<< "$INPUT" | fold -w 60)
echo; echo -e "${WHITE}Complimentary sequence:${NC}"
echo "$COMP"; echo
R_COMP=$(tr -d '\n' <<< "$COMP" | rev | fold -w 60)
echo -e "${WHITE}Reverse complimentary:${NC}" 
echo "$R_COMP"; echo

count_char() {
    local base_str=$(tr -dc "$1" <<< "$INPUT")
    echo "${#base_str}"
}

ADEN=$(count_char "A"); echo "Adenine (A): $ADEN"
GUAN=$(count_char "G"); echo "Guanine (G): $GUAN"
CYTO=$(count_char "C"); echo "Cytosine(C): $CYTO"
THYM=$(count_char "T"); echo "Thymine (T): $THYM"

# calculation for GC and AT Content
TOTAL=${#INPUT}
if (( TOTAL > 0 )); then
    GC_COUNT=$((GUAN+CYTO))
    GC_PCT=$(bc -l <<< "scale=2; $GC_COUNT * 100 / $TOTAL" )
    echo; echo -e "${WHITE}GC Content${NC}: $GC_PCT%"

    AT_COUNT=$((ADEN+THYM))
    AT_PCT=$(bc -l <<< "scale=2; $AT_COUNT * 100 / $TOTAL")
    echo -e "${WHITE}AT Content${NC}: $AT_PCT%"
fi
