#!/usr/bin/env bash
#
# ---------------------------------------------------------
# Batch video encoder for X265/HEVC conversion
# ---------------------------------------------------------
# Author:      Rish
# Date:        May 7, 2026
# License:     MIT
# ---------------------------------------------------------
#
# Colors
YW='\e[1;33m'   # yellow
GN='\e[1;32m'   # green
RD='\e[1;31m'   # red
GY='\e[1;30m'   # gray
WE='\e[1;37m'   # white
NC='\e[0m'      # normal

usage() {
    echo -e "Usage: vx265 [path/to/video directory] [Options]"
    echo -e "Options:"
    echo -e "  --mkv          Converts all .mkv files"
    echo -e "  --mp4          Converts all .mp4 files"
    echo -e "  --m4v          Converts all .m4v files"
    echo -e "  -h, --help     Display this help message"
}

# Check if at least two arguments are provided
(($# < 2)) && { usage; exit 1; }

chk_dpdc() {
    if ! command -v ffmpeg &> /dev/null; then 
        echo -e "${RD}> Install ffmpeg first${NC}"
        echo "> Run: pkg install ffmpeg"; exit 1
    fi
}

main() {
    local format="$1"
    echo -e "${WE}Converting '${format^^}s' into x265 codec...\n${NC}"

    for file in "$VID_DIR"/*.${format}; do
        [[ -e "$file" ]] || { echo "No '${format^^}' files found."; return; }
        echo -e "${GY} Processing '$file'...${NC}"
        ffmpeg -hide_banner -loglevel error -i "$file" -c:a copy -c:v libx265 "${file%.*}_new.${format}"
        sleep 5
    done

    printf "\n${GN}Completed, time elapsed: ${NC}%02dh %02dm %02ds\n" $((SECONDS/3600)) $(((SECONDS/60)%60)) $((SECONDS%60))
}

chk_dpdc 

VID_DIR="$1"
EXTENSION="$2"

if [[ ! -d "$VID_DIR" ]]; then
    echo -e "${RD}E:${NC} Directory '$VID_DIR' not found."
    exit 1
fi

case $EXTENSION in
    --mkv ) main "mkv" ;; 
    --mp4 ) main "mp4" ;;
    --m4v ) main "m4v" ;; 
    --ts ) main "ts" ;;
    --help | -h ) usage ;;
    *) echo -e "${RD}Invalid option:${NC} '${YW}$EXTENSION${NC}'"
       echo -e "Try 'vx265 --help' for more information."
       exit 1 ;;
esac
